name: Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    name: Run Gradle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Build & run functional tests
        run: ./gradlew -i -S build functionalTest

      - name: Publish unit test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: gap-unit-tests-${{ steps.aem-version.outputs.value }}
          path: build/reports/tests/test

      - name: Publish functional test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: gap-functional-tests-${{ steps.aem-version.outputs.value }}
          path: build/reports/tests/functionalTest